class Configuration:

    WINDOW_WIDTH = 700
    WINDOW_HEIGHT = 700
    BLOCK_SIZE = WINDOW_WIDTH // 7
    PLATEAU_WIDTH = WINDOW_WIDTH * 7 // 5
    PLATEAU_HEIGHT = WINDOW_HEIGHT * 7 // 5
    LINE_COUNT = WINDOW_HEIGHT // BLOCK_SIZE
    COLUMN_COUNT = WINDOW_WIDTH // BLOCK_SIZE

